#
# Module manifest for module 'PSSQLBulkCopy'
#
# Generated by: neko3cs
#
# Generated on: 2024/02/26
#

@{
  RootModule        = 'PSSQLBulkCopy.dll'
  ModuleVersion     = '1.0.0'
  GUID              = 'b75402ba-182f-4c0d-a7c2-08d34731b955'
  Author            = 'neko3cs'
  CompanyName       = 'Unknown'
  Copyright         = '(c) neko3cs. All rights reserved.'
  Description       = '.NETのSQLBulkCopyを実行します。テーブル名とCSVファイルパスを指定することで任意のテーブルにCSVの値を登録することが出来ます。'
  FunctionsToExport = @()
  CmdletsToExport   = @('Invoke-SqlBulkCopy')
  VariablesToExport = '*'
  AliasesToExport   = @()
  PrivateData       = @{
    PSData = @{
      Tags       = @('SqlBulkCopy', 'SQLServer')
      ProjectUri = "https://github.com/neko3cs/PSSQLBulkCopy"
    }
  }
}
